FROM node:20-alpine

ENV REACT_APP_GEMINI_KEY=AIzaSyB5Ua0D2N7iOHXpfjcJtSGZ4iD6PuAXWIc \
    REACT_APP_TMDB_KEY=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwYjMwY2U3Y2ZmYjVjNmY4YjJmYWZhYTUyMjc5MWEyYSIsIm5iZiI6MTcyOTc1NDg2MC42ODkzMDEsInN1YiI6IjY3MTI0YjM0MWYwZWE0NzE0ZWRjMDAwMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.tVBFU5DXjv40EzVYHVAOYhYVumKqpfW3VpjPEjgZrb8 \
    REACT_APP_FIREBASE_KEY=AIzaSyAaiHumx440Zk5Y3wK3h2Mask_bAmCX8fE

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

# EXPOSE 3000

CMD ["npm","start"]